## Note that this Makefile is provided for convenience, but
## is DEPRECATED.
## Copy config.h.old to config.h before using this.
## Running cmake will overwrite Makefile, so use
## either cmake OR this Makefile.
CFLAGS=-I$(GMXLDLIB)/../include
OPTIONS=-fopenmp -O3 -DHAVE_INLINE -DGSL_RANGE_CHECK_OFF -Wl,-as-needed 
# OPTIONS=-g
CC=gcc
CPP=g++
F77=gfortran
## Extra libs are not yet needed, but future versions will need their features.
## LIBS=-L${GMXLDLIB} -lgsl -lcblas -larpack -llapack -lblas -ldb_cxx -lpthread -lgmx -lgmxana 
LIBS=-L${GMXLDLIB} -lgsl -larpack -llapack -lblas -ldb_cxx -lpthread -lgmx -lgmxana -lboost_program_options
OPENCL_LIBS=-L/opt/intel/opencl-1.2-3.0.67279/lib64 -lOpenCL

TARGETS=auto_decomp_sparse \
angles_to_sincos \
auto_decomp_sparse_nystrom \
auto_heir_decomp_sparse \
bb_xtc_to_phipsi \
ca_xtc_to_thetaphi \
check_xtc \
contact_profile \
decomp_dense \
decomp_sparse \
decomp_sparse_nystrom \
dijkstra \
knn_data \
knn_data_sparse \
knn_rms \
make_gesparse \
make_sysparse \
rms_test \
split_xtc

OCL_TARGETS=knn_data_ocl

# Targets
all : $(TARGETS)

opencl : $(OCL_TARGETS)

# Executables
$(TARGETS) : % : %.o mdsctk.o
	$(CPP) $(CFLAGS) $(OPTIONS) $^ $(LIBS) -o $@

$(OCL_TARGETS) : % : %.o mdsctk.o mdsctk_ocl.o
	$(CPP) $(CFLAGS) $(OPTIONS) $^ $(LIBS) $(OPENCL_LIBS) -o $@

# Objects
%.o : %.cpp
	$(CPP) $(CFLAGS) $(OPTIONS) -c $< -o $@

clean :
	rm -f *.o

dist-clean : clean
	rm -f $(TARGETS) $(OCL_TARGETS)
